name: Hello Workflow
#trigger
on: 
  push:
    branches: [main]

jobs:
  greet:
    # where the jobs run. This is github runner. 
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to users
        run: echo " Hey, There,"
      - name: Greet user
        run: echo " $USER"
